image: julrich/docker_qt:latest

variables:
  BUILD_DIR: build_linux64_gcc-5_qt-5.6

build:
  stage: build
  script:
    - g++ --version
    - qmake --version
    - mkdir -p "$BUILD_DIR"
    - cd "$BUILD_DIR"
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make qt5promise
  #artifacts:
  #  paths:
  #    - mybinary

test:
  stage: test
  script:
    - mkdir -p "$BUILD_DIR"
    - cd "$BUILD_DIR"
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - cd tests
    - make # Build the tests
    - cd ..
    - make test # Run the tests
