image: julrich/docker_qt:latest

variables:
  BUILD_DIR: build_linux64_gcc-5_qt-5.6

build:
  stage: build
  script:
    - g++ --version
    - qmake --version
    - mkdir -p "$BUILD_DIR"
    - cd "$BUILD_DIR"
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
  #artifacts:
  #  paths:
  #    - mybinary
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - mkdir -p "$BUILD_DIR"
    - cd "$BUILD_DIR"
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make test
